# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - azure-pipeline-docker
  paths:
    include:
    - apis/poi

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'apis/poi/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'devopsoh/api-poi'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: 'apis/poi/web/Dockerfile'

- task: CreateWorkItem@1
  condition: failed() # this job will only run if Foo fails
  inputs:
    workItemType: 'Issue'
    title: 'WI_Issue'
    associate: true
