# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - apis/poi
    
pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'apis/poi/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'devopsoh/api-poi'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'apis/poi/web/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: CreateWorkItem@1
  condition: failed() # this job will only run if Foo fails
  inputs:
    workItemType: 'Issue'
    title: 'WI_Issue'
    associate: true
